### ISSUE TITLE
部分安卓内核会有子元素溢出的bug

### ISSUE THREAD

**Issue by zephyrpersonal** [wen911119/preact-studio#5]
查到问题可能在这行，添加 `className={className.flex1}` 可修复。

from

https://github.com/wen911119/preact-studio/blob/a3e36c41c711a943cc802aee6ff8506fcd7d77f4/packages/preact-m-form-component/formRow.js#L32

to

```js
<SlotRowView padding={padding} bgColor={bgColor} slot={slot} className={className.flex1}>
```

**Comment by wen911119** [comment]
> 查到问题可能在这行，添加 `className={className.flex1}` 可修复。
> 
> from
> 
> https://github.com/wen911119/preact-studio/blob/a3e36c41c711a943cc802aee6ff8506fcd7d77f4/packages/preact-m-form-component/formRow.js#L32
> 
> to
> 
> ```js
> <SlotRowView padding={padding} bgColor={bgColor} slot={slot} className={className.flex1}>
> ```

**Comment by wen911119** [comment]
改完了，升级到1.10.19.
最新的布局套件现在改成css变量的实现方式了，表单升级到用配置自动生成的形式了。
有时间我再更新下，或者重新开个ts的库

**Comment by zephyrpersonal** [comment]
> 改完了，升级到1.10.19.
> 最新的布局套件现在改成css变量的实现方式了，表单升级到用配置自动生成的形式了。
> 有时间我再更新下，或者重新开个ts的库

ts大法好，🤣
